### Get all products
GET http://localhost:8080/api/v1/products
Accept: application/json

###

### Get product by ID
GET http://localhost:8080/api/v1/products/5
Accept: application/json

###

### Create a new product
POST http://localhost:8080/api/v1/products
Content-Type: application/json

{
  "productName": "MacBook Pro",
  "productPrice": 215000,
  "quantity": 35
}

###

### Update an existing product
PUT http://localhost:8080/api/v1/products/4
Content-Type: application/json

{
  "productName": "Updated Product",
  "productPrice": 200,
  "quantity": 30
}

###

### Delete a product
DELETE http://localhost:8080/api/v1/products/1

###